export const colors = [
    {"letter": "a", "bgColor": "#FFC0CB", "fontColor": "#000000"},
    {"letter": "b", "bgColor": "#008080", "fontColor": "#FFFFFF"},
    {"letter": "c", "bgColor": "#800080", "fontColor": "#FFFFFF"},
    {"letter": "d", "bgColor": "#F0E68C", "fontColor": "#000000"},
    {"letter": "e", "bgColor": "#00FF00", "fontColor": "#000000"},
    {"letter": "f", "bgColor": "#FFA500", "fontColor": "#000000"},
    {"letter": "g", "bgColor": "#00FFFF", "fontColor": "#000000"},
    {"letter": "h", "bgColor": "#FF69B4", "fontColor": "#FFFFFF"},
    {"letter": "i", "bgColor": "#4B0082", "fontColor": "#FFFFFF"},
    {"letter": "j", "bgColor": "#FFD700", "fontColor": "#000000"},
    {"letter": "k", "bgColor": "#800000", "fontColor": "#FFFFFF"},
    {"letter": "l", "bgColor": "#FF00FF", "fontColor": "#FFFFFF"},
    {"letter": "m", "bgColor": "#000080", "fontColor": "#FFFFFF"},
    {"letter": "n", "bgColor": "#ADD8E6", "fontColor": "#000000"},
    {"letter": "o", "bgColor": "#FF6347", "fontColor": "#FFFFFF"},
    {"letter": "p", "bgColor": "#008000", "fontColor": "#FFFFFF"},
    {"letter": "q", "bgColor": "#FA8072", "fontColor": "#FFFFFF"},
    {"letter": "r", "bgColor": "#FFFF00", "fontColor": "#000000"},
    {"letter": "s", "bgColor": "#0000FF", "fontColor": "#FFFFFF"},
    {"letter": "t", "bgColor": "#FF4500", "fontColor": "#FFFFFF"},
    {"letter": "u", "bgColor": "#800080", "fontColor": "#FFFFFF"},
    {"letter": "v", "bgColor": "#00FF7F", "fontColor": "#000000"},
    {"letter": "w", "bgColor": "#008080", "fontColor": "#FFFFFF"},
    {"letter": "x", "bgColor": "#FF1493", "fontColor": "#FFFFFF"},
    {"letter": "y", "bgColor": "#008000", "fontColor": "#FFFFFF"},
    {"letter": "z", "bgColor": "#FF69B4", "fontColor": "#FFFFFF"}
  ]
  